#+TITLE: Funciones: ejercicios propuestos
#+AUTHOR: 
#+DATE: 
#+SETUPFILE: configEjercicios.org

* Áreas de figuras geométricas
Escribe una función que calcule el área de un círculo, un triángulo o un cuadrado. La función empleará, a su vez, una función diferente definida para cada caso.

* Conversión de temperaturas
 Escribe una función para realizar la conversión de temperaturas. La función trabajará a partir de un valor (número real) y una letra. La letra indica la escala en la que se introduce esa temperatura. Si la letra es 'C', la temperatura se convertirá de grados centígrados a Fahrenheit. Si la letra es 'F' la temperatura se convertirá de grados Fahrenheit a grados Centígrados. Se usarán 2 funciones auxiliares, =cent2fahr= y =fahr2cent= para convertir de una escala a otra. Estas funciones aceptan un parámetro (la temperatura en una escala) y devuelven el valor en la otra escala. 

Nota: La relación entre ambas escalas es $T_F = 9/5 * T_C + 32$

* Tablas de multiplicar
Construye un programa que muestre por pantalla las tablas de multiplicar del 1 al 10, a partir de dos funciones específicas. La primera función debe devolver el producto de dos valores numéricos enteros dados como parámetros. La segunda función debe mostrar por pantalla la tabla de multiplicar de un número dado como parámetro.

* Números combinatorios

Escribe una función que calcule y muestre en pantalla el número combinatorio a partir de los valores =n= y =k=.

\[
nk = \frac{n!}{(n - k)! \cdot k!}
\]

Esta función debe estar construida en base a dos funciones auxiliares, una para calcular el factorial de un número, y otra para calcular el número combinatorio.

* Fibonacci

Escribe una *función recursiva* que genere los =n= primeros términos de la serie de Fibonacci. Esta función aceptará el número entero =n= como argumento. Este valor debe ser positivo, de forma que si el usuario introduce un valor negativo la función devolverá un error.

Nota: En la serie de Fibonacci los dos primeros números son 1, y el resto se obtiene sumando los dos anteriores: $1, 1, 2, 3, 5, 8, 13, 21, \ldots$

* Serie de Taylor

 Escribe un conjunto de funciones para calcular la aproximación de $e ^ {-x}$ mediante el desarrollo de Taylor:

 \[
 e^{-x} = 1 + \sum_{i = 1}^\infty \frac{(-x)^n}{n!}
 \]

 La función principal acepta como argumentos el valor del número real =x= y el número de términos deseados. Se basará en otras tres funciones: 

- =factorial= calcula el factorial de un número entero =n=.

- =potencia= calcula la potencia =n= de un número real =x=.

- =exponencial= calcula la aproximación anterior de un número real =x= usando =n= términos de la serie de Taylor. 

